apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "role-staging"
        vault.hashicorp.com/agent-inject-secret-.env: "secret"
        vault.hashicorp.com/secret-volume-path-.env: "/tmp"
        vault.hashicorp.com/agent-inject-template-.env: |
          {{- $stack := "staging" }}
          {{- with secrets (printf "secret/%s" $stack) }}
          {{- range $secret := . }}
          {{- if not (eq $secret  "event/") }}
          {{ with secret (printf "secret/%s/%s" $stack $secret) }}
          {{ (printf "# %s Environment Variables" $secret) -}}
          {{ range $k, $v := .Data.data }}
          {{$k}}={{$v -}}
          {{ end }}{{ end }}{{ end }}{{ end }}{{ end }}
          {{ if eq $stack "staging" }}
          {{ with secret "secret/staging/event/default" }}
          {{ "# Staging Environment Variables" -}}
          {{ range $k, $v := .Data.data }}
          {{$k}}={{$v -}}
          {{ end }}{{ end }}
          {{ else }}
          {{ with secrets "secret/prod" }}
          {{ range $secret := . }}
          {{ with secret (printf "secret/prod/%s"  $secret) }}
          {{ (printf "# %s Environment Variables" $secret) -}}
          {{ range $k, $v := .Data.data }}
          {{$k}}={{$v -}}
          {{ end }}{{ end }}{{ end }}{{ end }}{{ end }}
    spec:
      serviceAccountName: internal-app
      containers:
        - name: web
          image: alpine:latest
          args: ["sh", "-c", "cat /tmp/.env && sleep inf"]
