name: Vault 
description: vault

inputs:
  secrets-name:
    description: Vault Command to Execute
    required: true
  roleId:
    description: Vault roleId
    required: true
  secretId:
    description: Vault secretId
    required: true
  secrets-path:
    description: build-args
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        IFS=':' read -r -a arrayPath <<< "$SECRET_PATH"
        IFS=':' read -r -a arrayName <<< "$SECRET_PATH"
        echo $arrayPath
      env:
        SECRET_PATH: ${{ inputs.secrets-path }}
        SECRET_NAME: ${{ inputs.secrets-name }}
    - name: Import Secrets
      id: secrets
      uses: hashicorp/vault-action@v2.3.1
      with:
        exportEnv: false
        url: https://vault.outmind.fr
        method: approle
        roleId: ${{ inputs.roleId }}
        secretId: ${{ inputs.secretId }}
        secrets: |
          secret/data/prod/box BOX_CLIENT_ID;
    - shell: bash
      run: env
      env:
        POOP: ${{ steps.secrets.outputs.TURBO_TOKEN }}
    - shell: bash
      run: env
      env:
        TEST: ${{ inputs.build-args }}

        