name: anotther

on:
  pull_request:
  push:
    branches: [main]
    tags: [v*]
  workflow_dispatch:
    inputs:
      deploy:
        description: Set to `true` to deploy to K8s
        required: false

jobs:
  another:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to current branch
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
        with:
          fetch-depth: 2
      - id: abc
        run: |
          git diff --name-only HEAD HEAD~1 | grep apps/testing.js
          if [ "$?" -eq 0 ]
          then
            echo "::set-output name=migration::${{ github.ref == 'refs/heads/main' }}"
          else
            echo "::set-output name=migration::false"
      - run: |
          echo $migration
        env:
          MIGRATION: ${{steps.abc.outputs.migration}}
