name: anotther

on:
  pull_request:
  push:
    branches: [main]
    tags: [v*]
  workflow_dispatch:
    inputs:
      deploy:
        description: Set to `true` to deploy to K8s
        required: false

jobs:
  another:
    runs-on: ubuntu-latest
    steps:
      - uses: jitterbit/get-changed-files@v1
        id: abc
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Printing
        if: contains(steps.abc.outputs.modified,'apps/test.js')
        run: |
          echo "${{ steps.abc.outputs.modified }}"
