name: anotther

on:
  pull_request:
  push:
    branches: [main]
    tags: [v*]
  workflow_dispatch:
    inputs:
      deploy:
        description: Set to `true` to deploy to K8s
        required: false

jobs:
  another:
    runs-on: ubuntu-latest
    steps:
      - uses: jitterbit/get-changed-files@v1
        id: files
        with:
          format: 'space-delimited'
      - id: migration
        run: |
          echo ::set-output name=value::${{contains(steps.files.outputs.modified,'apps/test.js')}}
      - run: echo $MIGRATION
        env:
          MIGRATION: ${{steps.migration.outputs.migration}}
