name: Build, test & deploy

on:
  pull_request:
  push:
    branches: [main]
    tags: [v*]
  workflow_dispatch:
    inputs:
      deploy:
        description: Set to `true` to deploy to K8s
        required: false

jobs:

  build_ssh:
    name: Build SSH Image
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.matrix_prep.outputs.matrix) }}
    steps:
        # Checkout current branch
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      # Get Vault Secrets
      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v2.3.1
        with:
          exportEnv: false
          url: https://vault.outmind.fr
          method: approle
          roleId: ${{ secrets.ROLE_ID }}
          secretId: ${{ secrets.SECRET_ID }}
          secrets: |
            secret/data/${{ matrix.stack }}/ssh SSH_PUBLIC_KEY_RETOOL ;
            secret/data/${{ matrix.stack }}/ssh SSH_PUBLIC_KEY ;
            secret/data/${{ matrix.stack }}/postgres POSTGRES_URL
      - name: test
        id: test
        uses: ./.github/actions/test
        with:
          matrix: "marwen"

      - shell: bash
        run: |
          echo "$OUTPUT"
        env:
          OUTPUT: ${{ steps.test.outputs.dynamic-values.marwen }}

  debug:
    runs-on: ubuntu-latest
    steps:
      - env:
          NEEDS: ${{ toJSON(needs) }}
        run: echo "$NEEDS"