name: Build, test & deploy

on:
  pull_request:
  push:
    branches: [main]
    tags: [v*]
  workflow_dispatch:
    inputs:
      deploy:
        description: Set to `true` to deploy to K8s
        required: false

jobs:

  build_ssh:
    name: Build SSH Image
    runs-on: ubuntu-latest
    steps:
        # Checkout current branch
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - name: test
        id: test
        uses: ./.github/actions/test
        with:
          matrix: "marwen ${{ github.ref_type }}"

      - shell: bash
        run: |
          echo "$OUTPUT"
        env:
          OUTPUT: ${{ steps.test.outputs.dynamic-values.marwen.value }}

  debug:
    runs-on: ubuntu-latest
    steps:
      - env:
          NEEDS: ${{ toJSON(needs) }}
        run: echo "$NEEDS"