name: testing pipeline

on:
  push:
    branches:
      - "main"

jobs:
  backend:
    runs-on: ubuntu-20.04
    steps:
      - uses: ./.github/actions/vault-cli
        with:
          roleId: ${{ secrets.ROLE_ID }}
          secredId: ${{ secrets.SECRET_ID }}
          command: vault kv put secret/testing test=test
      - uses: actions/checkout@v2
      - name: Imports Secrets
        id: secretsJob
        uses: hashicorp/vault-action@v2.3.1
        with:
          url: https://vault.outmind.fr
          method: approle
          roleId: bf5548e5-50fb-42f4-37fd-81ce0899242f
          secretId: beb9c24c-54ab-bf04-6634-a7aa7f57ec7f
          secrets: |
                secret/data/prod/box BOX_CLIENT_ID | BOX_CLIENT_ID ;
      - shell: bash
        run: |
          export | grep EMBEDDER_URL



