name: testing pipeline

on:
  push:
    branches:
      - "main"

jobs:
  backend:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - shell: bash
        run: |
          echo "hello"
          git config --global user.name 'Marwennnne'
          git config --global user.email 'marwen.guesmi@insat.u-carthage.tn'
          echo "hello world dsqdsqq" > file.txt
          git add -A
          git commit -m "dsqdsqdsqsqd"
          git push 
