name: testing pipeline

on:
  push:
    branches:
      - "main"

jobs:
  backend:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Imports Secrets
        id: secretsJob
        uses: hashicorp/vault-action@v2.3.1
        with:
          url: https://vault.outmind.fr
          token: ${{ secrets.VaultToken }}
          secrets: |
                secret/data/staging/embedder EMBEDDER_URL | EMBEDDER_URL ;

      - name: echo secrets
        shell: bash
        run: |
          echo ${{steps.secretsJob.outputs.EMBEDDER_URL}}

      - name: Vault
        uses: ./.github/actions/vaultcli
        with:
          command: |
            vault kv put secret/preview/pr-${{ false && '3' || format('pr-{0}', github.event.number)   }} test=test \
            marwen=marwen \
            guesmi=guesmi
          token: ${{ secrets.VaultToken }}

