name: testing pipeline

on:
  push:
    branches:
      - "main"

jobs:
  backend:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        stack: [app, bouygues, tnp, valgo,valrgo]
    steps:
      - name: Compute version
        id: version
        run: echo "::set-output name=version::testmarwen"
      - shell: bash
        run: |
          echo ${{ github.ref }}
      - uses: actions/checkout@v2
      - name: Imports Secrets
        id: secretsJob
        uses: hashicorp/vault-action@v2.3.1
        with:
          url: https://vault.outmind.fr
          method: approle
          roleId: bf5548e5-50fb-42f4-37fd-81ce0899242f
          secretId: beb9c24c-54ab-bf04-6634-a7aa7f57ec7f
          secrets: |
            secret/data/prod/box BOX_CLIENT_ID | BOX_CLIENT_ID ;
      - shell: bash
        run: |
          sed -Ei "s|\\$stack := \"staging\"|\\$stack := \"${{ matrix.stack }}\"|g" test.yaml
      - shell: bash
        run: |
          cat test.yaml
      - uses: ./.github/actions/vaultcli
        with:
          roleId: ${{ secrets.ROLE_ID }}
          secretId: ${{ secrets.SECRET_ID }}
          command: vault kv put secret/testing/${{ matrix.stack}} test=${{ steps.version.outputs.version }}

      - shell: bash
        run: |
          git config --global user.name 'Marwennnne'
          git config --global user.email 'marwen.guesmi@insat.u-carthage.tn'
          echo "hello world" > file.txt
          git commit -am "test test"
          git push 
