name: anotther

on:
  pull_request:
  push:
    branches: [main]
    tags: [v*]
  workflow_dispatch:
    inputs:
      deploy:
        description: Set to `true` to deploy to K8s
        required: false


jobs:
  kubeconfig:
    runs-on: ubuntu-latest
    steps:
      - run: |
          cat > kubeconfig.yaml <<EOF
          apiVersion: v1
          clusters:
          - cluster:
              certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUyTlRJNE5qUTNPVEV3SGhjTk1qSXdOVEU0TURrd05qTXhXaGNOTXpJd05URTFNRGt3TmpNeApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUyTlRJNE5qUTNPVEV3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFUbWxUM29XZ0VaUEY4Tko1Qkk1VDBJUmIxeHhxTy84OU9xVW4wMk9LemwKU1o3MTArL0NjMWROQ2FweWg5akFlWGdidkFVUHR0Nkh4d2hwYy8wQVRFZlhvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVTV1VkpGcjlnL0UxdTAzYWF1QnRqCjRJdVFuRGN3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQU0vZGhpeXpTLzA0ek15YjBCZkxtTDBRRGRGbGJrSXYKWEV2VjN6WjAxUnBmQWlCRk5ObjBOSXkvU0JPeTc1ckp2UDZlNTdNc0Q3WTM4RklMWmpqTEpjbmVsQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
              server: https://a4e2e35fb820b47f2b9cf44a5a6c5aed-1317235581.eu-west-3.elb.amazonaws.com
            name: local
          contexts:
          - context:
              cluster: local
              namespace: default
              user: user
            name: Default
          current-context: Default
          kind: Config
          preferences: {}
          users:
          - name: user
            user:
              client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrVENDQVRlZ0F3SUJBZ0lJYm1YR1M3a0pIbVV3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOalV5T0RZME56a3hNQjRYRFRJeU1EVXhPREE1TURZek1Wb1hEVEl6TURVeApPREE1TURZek1Wb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJQYkdCVkIxUFNpZUxoT0wKNTJ4UVJUZzFFVWxpTUErMnlrL005T09wZDVLNlEvWEhGbXFGNHRHcEFscVZ3QTc1eGlBNHp5QS9PTVJ1YmM2ZwpBclV0alMyalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCU0VmM05CdEp0dXVYdlM2ZnRnbGZJMkQ5SGhkekFLQmdncWhrak9QUVFEQWdOSUFEQkYKQWlCKzNMSGc1ZytWanJwZDUrSkRVRUc5MFhJMS9ER2MzeklPODlhWXEzSzYvZ0loQUtnNEgxT3VMWXNmRG5teAp5MmlQR0F6T0RtUFpvM1FLUGJRY3FUeUNqRldFCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlRENDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUyTlRJNE5qUTNPVEV3SGhjTk1qSXdOVEU0TURrd05qTXhXaGNOTXpJd05URTFNRGt3TmpNeApXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUyTlRJNE5qUTNPVEV3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFRbWZRWE5YUGNBTktSS0doblQvQXJBSHNCeWdCOFVtTUdVVGNFV3ZHWEcKNDRHQk54bDU2VEt3T1R4aUczYnl3Y0VNRzJ2M0VPRTh4ZDVjMitYTGs0bFJvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVWhIOXpRYlNiYnJsNzB1bjdZSlh5Ck5nL1I0WGN3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQU55a0xPTkx1Y3kzQU56KzdqVHJ6TW11SFNHUTlpaGgKVmFCMlVRUUlCQmx2QWlFQWpZckZKWkQ5Ly9tS2YwYjhEYWF2VERSeVdUK3VkSVlzbW96NGw0endQVXM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
              client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUl1eUFFUW03UGg1TlBQOWo2UE1rVzh0LzZiWDg2bmNPbm9ZMjNaWTFzZUpvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFOXNZRlVIVTlLSjR1RTR2bmJGQkZPRFVSU1dJd0Q3YktUOHowNDZsM2tycEQ5Y2NXYW9YaQowYWtDV3BYQUR2bkdJRGpQSUQ4NHhHNXR6cUFDdFMyTkxRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
          EOF
          cat >> $GITHUB_ENV <<EOF
          KUBECONFIG=kubeconfig.yaml
      - run: kubectl get pods

