name: need

on:
  pull_request:
  push:
    branches: [main]
    tags: [v*]
  workflow_dispatch:
    inputs:
      deploy:
        description: Set to `true` to deploy to K8s
        required: false


jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - id: needs
        run: echo "hello"
         
  two:
    runs-on: ubuntu-latest
    needs: one
    steps:
      - run: exit(1)

  three:
    runs-on: ubuntu-latest
    needs: two
    if:  always() && !failure()
    steps:
      - run: |
         echo "::set-output name=matrix::{\"stack\":  'one' }"

