name: my workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3
    - name: Import Secrets
      id: secrets
      uses: hashicorp/vault-action@v2.3.1
      with:
        url: https://vault.outmind.fr
        method: approle
        roleId: ${{ secrets.ROLE_ID }}
        secretId: ${{ secrets.SECRET_ID }}
        secrets: |
          secret/data/prod/elastic-apm ELASTIC_APM_SERVER_URL ;
          secret/data/prod/apple APPLE_DEVELOPER_CERTIFICATE ;
          secret/data/prod/apple APPLE_DEVELOPER_CERTIFICATE_PASSWORD ;
          secret/data/prod/apple APPLE_DEVELOPER_ID ;
          secret/data/prod/apple APPLE_DEVELOPER_ID_PASSWORD ;
          secret/data/prod/apple APPLE_ORGANIZATION_ID ;
          secret/data/prod/aws-ci AWS_ACCESS_KEY_ID_CI_PUBLISH_DESKTOP | AWS_ACCESS_KEY_ID ;
          secret/data/prod/aws-ci AWS_SECRET_ACCESS_KEY_CI_PUBLISH_DESKTOP | AWS_SECRET_ACCESS_KEY ;
          secret/data/prod/code-signing CODE_SIGNING_CERT ;
          secret/data/prod/code-signing CODE_SIGNING_PRIVATE_KEY
    - shell: bash
      run: |
        env
