name: my workflow
on: push
jobs:
  build_ssh:
    runs-on: ubuntu-latest
    outputs:
      staging: ${{ steps.output.outputs.staging }}
    steps:
      - shell: bash
        id: output
        run: echo ::set-output name=staging::hello
  echo:
    name: Retrieve secrets from vault
    runs-on: ubuntu-latest
    needs: build_ssh
    strategy:
      matrix:
        stack: [ staging ]
    steps:
      - shell: bash
        run: |
          echo $env
        env:
          env: ${{ needs.build_ssh.outputs[ matrix.stack ] }}